name: group_grit
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# --------- PACKAGES --------- #
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  #Utility packages

  
  #Icons
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.4.1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  video_uploader: ^1.3.0
  file_picker: ^9.0.0 # per selezionare video dai file locali
  video_player: ^2.9.2
  flutter_translation_sheet: ^1.0.34
  flutter_gen: ^5.9.0
  dotted_border: ^2.1.0
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  rxdart: ^0.28.0 
  firebase_analytics: ^11.4.2
  lottie: ^3.1.0
  firebase_crashlytics: ^4.3.3
  mixpanel_flutter: ^2.3.4
  app_tracking_transparency: ^2.0.6+1
  package_info_plus: ^8.2.1
  sign_in_with_apple: ^6.1.4
  awesome_notifications: ^0.10.1
  firebase_messaging: ^15.2.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  firebase_remote_config: ^5.4.2
  url_launcher: ^6.3.1
  chewie: ^1.11.0
  crypto: ^3.0.6
  
dependency_overrides:
  web: ^1.1.0
  intl: ^0.19.0




# --------- ./ PACKAGES END ---------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/images/logoIcon.jpg"
    



  #flutter_lints: ^5.0.0


# --------- LOCAL ASSETS ---------- #

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/backLoginImage.jpg
    - assets/lotties/Training.json
    - assets/lotties/NoData.json
    - assets/images/logo.png
    - assets/images/logoIcon.jpg
