// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_X0Onn1bYsFlRMJIbj1p0Ztc-bazLijg',
    appId: '1:255103648172:web:b329c63b5318fd0192fa09',
    messagingSenderId: '255103648172',
    projectId: 'group-grit-app',
    authDomain: 'group-grit-app.firebaseapp.com',
    storageBucket: 'group-grit-app.firebasestorage.app',
    measurementId: 'G-9F1Z8XKETQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5A1lAnZm8n-niDHT4HsPGbHTWfCIS48s',
    appId: '1:255103648172:android:15a76a123b656e4092fa09',
    messagingSenderId: '255103648172',
    projectId: 'group-grit-app',
    storageBucket: 'group-grit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8m-2lua_UwvKkzNr5ZXMAykF8g3xCueQ',
    appId: '1:255103648172:ios:660e6a0af068933c92fa09',
    messagingSenderId: '255103648172',
    projectId: 'group-grit-app',
    storageBucket: 'group-grit-app.firebasestorage.app',
    iosBundleId: 'com.example.groupGrit',
  );
}
